export interface OfficialQqBotApiDefinition {
  name: string
  category: string
}

const catalog: Record<string, string[]> = {
  '共享入口（自动映射）': [
    'get_login_info',
    'get_group_list',
    'get_friend_list',
    'get_group_info',
    'get_group_member_info',
    'get_group_member_list',
    'get_friend_info',
    'send_group_message',
    'send_private_message',
    'send_private_stream_message',
    'recall_group_message',
    'recall_private_message',
    'upload_group_file',
    'upload_private_file',
    'set_group_kick',
    'set_group_ban',
    'get_group_ban',
    'get_group_join_requests',
    'set_group_add_request',
    'get_official_menu',
    'set_official_menu',
    'get_official_panels',
    'create_official_panel',
    'set_official_panel',
    'send_channel_message',
    'create_guild_dm',
    'send_guild_dm',
    'recall_channel_message',
    'get_guild_list',
    'set_guild_mute',
    'set_guild_member_mute',
    'set_guild_members_mute',
    'get_group_bot_state',
    'get_join_approval_strategy',
    'get_resource_temp_url',
    'ack_official_interaction',
  ],
  '消息': [
    'POST /v2/groups/{group_openid}/messages',
    'POST /v2/users/{openid}/messages',
    'POST /v2/users/{openid}/stream_messages',
    'DELETE /v2/groups/{group_openid}/messages/{message_id}',
    'DELETE /v2/users/{openid}/messages/{message_id}',
    'POST /channels/{channel_id}/messages',
    'POST /users/@me/dms',
    'POST /dms/{guild_id}/messages',
    'DELETE /channels/{channel_id}/messages/{message_id}',
  ],
  '富媒体': [
    'POST /v2/groups/{group_openid}/files',
    'POST /v2/users/{openid}/files',
    'POST /v2/groups/{group_id}/upload_prepare',
    'POST /v2/groups/{group_id}/upload_part_finish',
    'POST /v2/users/{user_id}/upload_prepare',
    'POST /v2/users/{user_id}/upload_part_finish',
  ],
  '群聊管理': [
    'GET /v2/groups/{group_openid}/info',
    'GET /v2/groups/{group_openid}/bot_state',
    'GET /v2/groups/{group_openid}/members',
    'GET /v2/groups/{group_openid}/members/{member_openid}',
    'POST /v2/groups/{group_openid}/batch_remove_members',
    'GET /v2/groups/{group_openid}/restrict_chat_setting',
    'POST /v2/groups/{group_openid}/restrict_chat_setting',
    'GET /v2/groups/{group_openid}/join_request_list',
    'POST /v2/groups/{group_openid}/approval_join_request/{member_openid}',
    'GET /v2/groups/{group_openid}/member_blacklist',
    'POST /v2/groups/{group_openid}/member_blacklist',
    'GET /v2/groups/join_approval_strategy',
    'POST /v2/groups/join_approval_strategy',
    'PATCH /v2/groups/join_approval_strategy/{strategy_id}',
    'DELETE /v2/groups/join_approval_strategy/{strategy_id}',
    'POST /v2/groups/join_approval_strategy/{strategy_id}/execute',
    'POST /v2/groups/join_approval_strategy/{strategy_id}/whitelist_users',
  ],
  '机器人菜单与面板': [
    'GET /v2/menu',
    'PUT /v2/menu',
    'GET /v2/panels',
    'POST /v2/panels',
    'GET /v2/panels/{panel_id}',
    'PUT /v2/panels/{panel_id}',
    'DELETE /v2/panels/{panel_id}',
    'PUT /v2/panels/{panel_id}/target',
    'PUT /interactions/{interaction_id}',
    'POST /v2/generate_url_link',
  ],
  '用户与频道': [
    'GET /users/@me',
    'GET /users/@me/guilds',
    'GET /guilds/{guild_id}',
    'GET /guilds/{guild_id}/channels',
    'POST /guilds/{guild_id}/channels',
    'GET /channels/{channel_id}',
    'PATCH /channels/{channel_id}',
    'DELETE /channels/{channel_id}',
    'PATCH /guilds/{guild_id}/mute',
    'PATCH /guilds/{guild_id}/members/{user_id}/mute',
    'GET /gateway',
    'GET /gateway/bot',
  ],
}

export const officialQqBotApiCatalog: OfficialQqBotApiDefinition[] = Object.entries(catalog)
  .flatMap(([category, names]) => names.map(name => ({ name, category })))
