package online.yudream.base.infra.installer.store;

import online.yudream.base.domain.installer.BootstrapConfigFile;
import online.yudream.base.domain.installer.repo.BootstrapConfigStore;
import online.yudream.base.domain.installer.valobj.BootstrapConfig;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;
import org.springframework.util.StringUtils;

import java.io.IOException;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.nio.file.AtomicMoveNotSupportedException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.nio.file.attribute.PosixFilePermissions;
import java.time.Instant;
import java.util.Properties;

/**
 * 引导配置文件存储实现：写入 {@code config/yudream-bootstrap.properties}（原子替换），
 * 容器部署时该目录必须以卷挂载持久化。
 */
@Component
public class LocalBootstrapConfigStore implements BootstrapConfigStore {

    private final String configuredLocation;

    public LocalBootstrapConfigStore(
            @Value("${" + BootstrapConfigFile.PROPERTY_LOCATION + ":}") String configuredLocation) {
        this.configuredLocation = configuredLocation;
    }

    @Override
    public boolean exists() {
        return Files.exists(location());
    }

    @Override
    public Path location() {
        if (StringUtils.hasText(configuredLocation)) {
            return Path.of(configuredLocation.trim());
        }
        return BootstrapConfigFile.locateDefault();
    }

    @Override
    public void save(BootstrapConfig config) {
        if (config == null || !StringUtils.hasText(config.mongoUri()) || !StringUtils.hasText(config.redisHost())) {
            throw new IllegalArgumentException("引导配置缺少数据库或 Redis 连接信息");
        }
        Path target = location();
        Properties props = new Properties();
        props.setProperty("spring.data.mongodb.uri", config.mongoUri());
        props.setProperty("spring.data.redis.host", config.redisHost());
        props.setProperty("spring.data.redis.port", String.valueOf(config.redisPort()));
        if (config.redisPassword() != null) {
            props.setProperty("spring.data.redis.password", config.redisPassword());
        }
        props.setProperty("spring.data.redis.database", String.valueOf(config.redisDatabase()));
        if (Boolean.TRUE.equals(config.redisSsl())) {
            props.setProperty("spring.data.redis.ssl.enabled", "true");
        }
        props.setProperty("yudream.credential.key", config.credentialKey());
        props.setProperty("snowflake.data-center-id", String.valueOf(config.snowflakeDataCenterId()));
        props.setProperty("snowflake.machine-id", String.valueOf(config.snowflakeMachineId()));
        props.setProperty("yudream.bootstrap.installed-at", Instant.now().toString());
        try {
            Files.createDirectories(target.toAbsolutePath().getParent());
            Path temp = target.resolveSibling(target.getFileName() + ".tmp");
            try (Writer writer = Files.newBufferedWriter(temp, StandardCharsets.UTF_8)) {
                props.store(writer, "YuDream Admin bootstrap configuration (generated by setup wizard)");
            }
            restrictOwnerOnly(temp);
            try {
                Files.move(temp, target, StandardCopyOption.REPLACE_EXISTING, StandardCopyOption.ATOMIC_MOVE);
            } catch (AtomicMoveNotSupportedException e) {
                Files.move(temp, target, StandardCopyOption.REPLACE_EXISTING);
            }
        } catch (IOException e) {
            throw new IllegalStateException("写入引导配置文件失败：" + target, e);
        }
    }

    private void restrictOwnerOnly(Path file) {
        try {
            Files.setPosixFilePermissions(file, PosixFilePermissions.fromString("rw-------"));
        } catch (UnsupportedOperationException | IOException ignored) {
            // Windows 文件系统不支持 POSIX 权限，保持默认即可
        }
    }
}
