package online.yudream.base.infra.system.security.service;

import com.fasterxml.jackson.core.type.TypeReference; import com.fasterxml.jackson.databind.ObjectMapper; import lombok.RequiredArgsConstructor; import online.yudream.base.domain.common.exception.BizException; import online.yudream.base.domain.system.security.aggregate.ExternalLoginProvider; import online.yudream.base.domain.system.security.service.ExternalLoginGateway; import org.springframework.stereotype.Service; import org.springframework.util.StringUtils; import java.net.URI; import java.net.URLEncoder; import java.net.http.*; import java.nio.charset.StandardCharsets; import java.time.Duration; import java.util.*;
@Service @RequiredArgsConstructor public class WwoyunExternalLoginGateway implements ExternalLoginGateway {
 private static final String ENDPOINT="https://login.wwoyun.cn/connect.php"; private final ObjectMapper objectMapper;
 public String authorizationUrl(ExternalLoginProvider p,String type,String state){Map<String,String> q=base(p,type);q.put("act","login");q.put("redirect_uri",callback(p,state));Map<String,Object> r=call(q);String url=text(r.get("url"));if(!StringUtils.hasText(url))throw new BizException("Wwoyun 未返回授权地址");return url;}
 public ExternalIdentity exchange(ExternalLoginProvider p,String type,String code){Map<String,String> q=base(p,type);q.put("act","callback");q.put("code",code);Map<String,Object> r=call(q);String uid=text(r.get("social_uid"));if(!StringUtils.hasText(uid))throw new BizException("Wwoyun 未返回第三方账号标识");return new ExternalIdentity(uid,text(r.get("nickname")),text(r.get("faceimg")),text(r.get("gender")),text(r.get("location")));}
 private Map<String,String> base(ExternalLoginProvider p,String type){Map<String,String> q=new LinkedHashMap<>();q.put("appid",p.getAppId());q.put("appkey",p.getAppKey());q.put("type",type);return q;} private String callback(ExternalLoginProvider p,String state){return p.getCallbackUrl()+(p.getCallbackUrl().contains("?")?"&":"?")+"state="+enc(state);}
 private Map<String,Object> call(Map<String,String> q){String url=ENDPOINT+"?"+q.entrySet().stream().map(e->enc(e.getKey())+"="+enc(e.getValue())).reduce((a,b)->a+"&"+b).orElse("");try{HttpResponse<String> r=HttpClient.newHttpClient().send(HttpRequest.newBuilder(URI.create(url)).timeout(Duration.ofSeconds(15)).GET().build(),HttpResponse.BodyHandlers.ofString());Map<String,Object> b=objectMapper.readValue(r.body(),new TypeReference<>(){});if(r.statusCode()/100!=2||!Objects.equals("0",text(b.get("code"))))throw new BizException("Wwoyun 调用失败："+Objects.toString(b.get("msg"),String.valueOf(r.statusCode())));return b;}catch(BizException e){throw e;}catch(Exception e){throw new BizException("Wwoyun 服务请求失败");}} private String text(Object v){return v==null?null:String.valueOf(v);}private String enc(String s){return URLEncoder.encode(Objects.toString(s,""),StandardCharsets.UTF_8);}}
