package online.yudream.base.infra.platform.plugin.service;

import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import online.yudream.base.application.platform.capability.service.CapabilityAppService;
import online.yudream.base.domain.platform.graph.aggregate.GraphConnection;
import online.yudream.base.domain.platform.graph.repo.GraphConnectionRepo;
import online.yudream.base.domain.platform.graph.service.GraphProjectionGateway;
import online.yudream.base.domain.platform.graph.valobj.*;
import online.yudream.base.plugin.spi.system.graph.*;
import org.springframework.stereotype.Service;
import org.springframework.util.StringUtils;

import java.util.List;
import java.util.Map;
import java.util.regex.Pattern;

/** Enforces active-table and plugin authorization before every SPI projection operation. */
@Service @Slf4j @RequiredArgsConstructor
public class PluginGraphFrameworkService {
    private static final String GRAPH_CAPABILITY_CODE="neo4j", GRAPH_CAPABILITY_NAME="Neo4j 图数据库";
    private static final int MAX_TABLES=100, MAX_PROJECTION_ITEMS=1_000, MAX_COMPLETE_NODES=20_000,
            MAX_COMPLETE_RELATIONSHIPS=50_000, MAX_PROJECTION_PROPERTIES=50, MAX_PROJECTION_TEXT_LENGTH=128,
            MAX_PROJECTION_PAGE_SIZE=100, MAX_COMPLETE_BYTES=8*1024*1024;
    private static final Pattern IDENTIFIER=Pattern.compile("[A-Za-z0-9._:-]{1,128}");
    private static final ObjectMapper JSON=new ObjectMapper();
    private final CapabilityAppService capabilityAppService; private final GraphConnectionRepo graphConnectionRepo; private final GraphProjectionGateway graphProjectionGateway;
    public PluginGraphService scoped(String pluginCode){return !StringUtils.hasText(pluginCode)?PluginGraphService.unavailable():new ScopedPluginGraphService(pluginCode.trim());}
    private final class ScopedPluginGraphService implements PluginGraphService {
        private final String pluginCode; private ScopedPluginGraphService(String pluginCode){this.pluginCode=pluginCode;}
        @Override public List<PluginGraphTable> tables(){try{ensureCapabilityEnabled();return graphConnectionRepo.findActiveAuthorizedByPluginCode(pluginCode,MAX_TABLES).stream().filter(t->t!=null&&t.active()&&t.authorizedFor(pluginCode)).map(PluginGraphFrameworkService.this::toSpiTable).toList();}catch(RuntimeException ignored){return List.of();}}
        @Override public PluginGraphBindingStatus bindingStatus(){try{ensureCapabilityEnabled();}catch(RuntimeException e){return PluginGraphBindingStatus.unavailable(PluginGraphErrorCode.CAPABILITY_UNAVAILABLE,"Graph capability is unavailable");}List<GraphConnection> tables=boundTables(pluginCode);if(tables.isEmpty())return PluginGraphBindingStatus.unavailable(PluginGraphErrorCode.TABLE_BINDING_NOT_FOUND,"No active graph table is bound to this plugin");if(tables.size()>1)return PluginGraphBindingStatus.unavailable(PluginGraphErrorCode.TABLE_BINDING_AMBIGUOUS,"Multiple active graph tables are bound to this plugin");return PluginGraphBindingStatus.available(toSpiTable(tables.getFirst()));}
        @Override public PluginGraphProjectionResult replaceProjection(PluginGraphProjectionRequest request){try{ensureCapabilityEnabled();}catch(RuntimeException e){return failure(PluginGraphErrorCode.CAPABILITY_UNAVAILABLE,"Graph capability is unavailable");}PluginGraphProjection p=null;try{p=validateProjection(request);return replaced(resolveTable(request.tableCode(),pluginCode),p);}catch(ProjectionFailure e){return failure(e.code,e.getMessage());}catch(IllegalArgumentException e){return failure(PluginGraphErrorCode.INVALID_PROJECTION,"Graph projection is invalid");}catch(RuntimeException e){logUnexpectedFailure("replaceProjection",pluginCode,p,e);return failure(PluginGraphErrorCode.PROJECTION_FAILED,"Graph projection replacement failed");}}
        @Override public PluginGraphProjectionView readProjection(PluginGraphProjectionViewRequest request){try{ensureCapabilityEnabled();}catch(RuntimeException e){return viewFailure(PluginGraphErrorCode.CAPABILITY_UNAVAILABLE,"Graph capability is unavailable",request);}GraphProjectionViewRequest r=null;try{r=validateViewRequest(request);return toSpi(graphProjectionGateway.readProjection(resolveTable(request.tableCode(),pluginCode),pluginCode,r));}catch(ProjectionFailure e){return viewFailure(e.code,e.getMessage(),request);}catch(IllegalArgumentException e){return viewFailure(PluginGraphErrorCode.INVALID_PROJECTION,"Graph projection view request is invalid",request);}catch(RuntimeException e){logUnexpectedFailure("readProjection",pluginCode,r,e);return viewFailure(PluginGraphErrorCode.PROJECTION_FAILED,"Graph projection read failed",request);}}
        @Override public PluginGraphProjectionResult replaceProjection(PluginGraphProjection request){try{ensureCapabilityEnabled();}catch(RuntimeException e){return failure(PluginGraphErrorCode.CAPABILITY_UNAVAILABLE,"Graph capability is unavailable");}PluginGraphProjection p=null;try{p=validateProjection(request);return replaced(resolveBoundTable(pluginCode),p);}catch(ProjectionFailure e){return failure(e.code,e.getMessage());}catch(IllegalArgumentException e){return failure(PluginGraphErrorCode.INVALID_PROJECTION,"Graph projection is invalid");}catch(RuntimeException e){logUnexpectedFailure("replaceProjectionBound",pluginCode,p,e);return failure(PluginGraphErrorCode.PROJECTION_FAILED,"Graph projection replacement failed");}}
        @Override public PluginGraphProjectionResult replaceCompleteProjection(PluginGraphCompleteProjection request){try{ensureCapabilityEnabled();}catch(RuntimeException e){return failure(PluginGraphErrorCode.CAPABILITY_UNAVAILABLE,"Graph capability is unavailable");}PluginGraphProjection p=null;try{p=validateCompleteProjection(request);return replaced(resolveBoundTable(pluginCode),p);}catch(ProjectionFailure e){return failure(e.code,e.getMessage());}catch(IllegalArgumentException e){return failure(PluginGraphErrorCode.INVALID_PROJECTION,"Graph projection is invalid");}catch(RuntimeException e){logUnexpectedFailure("replaceCompleteProjection",pluginCode,p,e);return failure(PluginGraphErrorCode.PROJECTION_FAILED,"Graph projection replacement failed");}}
        @Override public PluginGraphProjectionView readProjection(PluginGraphProjectionReadRequest request){try{ensureCapabilityEnabled();}catch(RuntimeException e){return viewFailure(PluginGraphErrorCode.CAPABILITY_UNAVAILABLE,"Graph capability is unavailable",request);}GraphProjectionViewRequest r=null;try{r=validateViewRequest(request);return toSpi(graphProjectionGateway.readProjection(resolveBoundTable(pluginCode),pluginCode,r));}catch(ProjectionFailure e){return viewFailure(e.code,e.getMessage(),request);}catch(IllegalArgumentException e){return viewFailure(PluginGraphErrorCode.INVALID_PROJECTION,"Graph projection view request is invalid",request);}catch(RuntimeException e){logUnexpectedFailure("readProjectionBound",pluginCode,r,e);return viewFailure(PluginGraphErrorCode.PROJECTION_FAILED,"Graph projection read failed",request);}}
        private PluginGraphProjectionResult replaced(GraphConnection table,PluginGraphProjection projection){GraphProjectionReplaceResult r=graphProjectionGateway.replaceProjection(table,pluginCode,toDomain(projection));return new PluginGraphProjectionResult(true,r.namespace(),r.nodeCount(),r.relationshipCount(),null);}
    }
    private void ensureCapabilityEnabled(){capabilityAppService.ensureEnabled(GRAPH_CAPABILITY_CODE,GRAPH_CAPABILITY_NAME);}
    private PluginGraphProjection validateProjection(PluginGraphProjectionRequest r){if(r==null)throw new IllegalArgumentException("missing projection");validateIdentifier(r.tableCode());return validateProjection(new PluginGraphProjection(r.namespace(),r.versionId(),r.nodes(),r.relationships()));}
    private PluginGraphProjection validateProjection(PluginGraphProjection p){validateProjectionData(p);if(p.nodes().size()>MAX_PROJECTION_ITEMS||p.relationships().size()>MAX_PROJECTION_ITEMS)throw new IllegalArgumentException("too many projection items");return p;}
    private PluginGraphProjection validateCompleteProjection(PluginGraphCompleteProjection p){if(p==null)throw new IllegalArgumentException("missing complete projection");PluginGraphProjection projection=new PluginGraphProjection(p.namespace(),p.versionId(),p.nodes(),p.relationships());validateProjectionData(projection);if(projection.nodes().size()>MAX_COMPLETE_NODES||projection.relationships().size()>MAX_COMPLETE_RELATIONSHIPS)throw new ProjectionFailure(PluginGraphErrorCode.PROJECTION_LIMIT_EXCEEDED,"Complete projection exceeds item limit");try{if(JSON.writeValueAsBytes(projection).length>MAX_COMPLETE_BYTES)throw new ProjectionFailure(PluginGraphErrorCode.PROJECTION_LIMIT_EXCEEDED,"Complete projection exceeds payload limit");}catch(ProjectionFailure e){throw e;}catch(Exception e){throw new IllegalArgumentException("invalid complete projection",e);}return projection;}
    private void validateProjectionData(PluginGraphProjection p){if(p==null)throw new IllegalArgumentException("missing projection");validateIdentifier(p.namespace());validateIdentifier(p.versionId());p.nodes().forEach(n->validateItem(n.id(),n.type(),n.properties()));p.relationships().forEach(n->{validateItem(n.id(),n.type(),n.properties());validateIdentifier(n.sourceId());validateIdentifier(n.targetId());});}
    private GraphProjectionViewRequest validateViewRequest(PluginGraphProjectionViewRequest r){if(r==null)throw new IllegalArgumentException("missing projection view request");validateIdentifier(r.tableCode());return validateViewRequest(new PluginGraphProjectionReadRequest(r.namespace(),r.versionId(),r.nodePage(),r.nodeSize(),r.relationshipPage(),r.relationshipSize()));}
    private GraphProjectionViewRequest validateViewRequest(PluginGraphProjectionReadRequest r){if(r==null)throw new IllegalArgumentException("missing projection view request");validateIdentifier(r.namespace());validateIdentifier(r.versionId());validatePage(r.nodePage(),r.nodeSize());validatePage(r.relationshipPage(),r.relationshipSize());return new GraphProjectionViewRequest(r.namespace(),r.versionId(),r.nodePage(),r.nodeSize(),r.relationshipPage(),r.relationshipSize());}
    private void validateItem(String id,String type,Map<String,Object>properties){validateIdentifier(id);validateIdentifier(type);if(properties!=null&&properties.size()>MAX_PROJECTION_PROPERTIES)throw new IllegalArgumentException("too many properties");if(properties!=null)properties.forEach((k,v)->{validateIdentifier(k);validateProperty(v);});}
    private void validateProperty(Object value){if(value==null||value instanceof Boolean||value instanceof Number)return;if(value instanceof String text){if(text.length()>MAX_PROJECTION_TEXT_LENGTH)throw new IllegalArgumentException("invalid projection property");return;}if(value instanceof Map<?,?> map){if(map.size()>MAX_PROJECTION_PROPERTIES)throw new IllegalArgumentException("too many properties");map.forEach((key,nested)->{if(!(key instanceof String keyText))throw new IllegalArgumentException("invalid projection property");validateIdentifier(keyText);validateProperty(nested);});return;}if(value instanceof List<?> list){list.forEach(this::validateProperty);return;}throw new IllegalArgumentException("invalid projection property");}
    private void validateIdentifier(String value){if(!StringUtils.hasText(value)||!IDENTIFIER.matcher(value).matches())throw new IllegalArgumentException("invalid identifier");} private void validatePage(int page,int size){if(page<1||size<1||size>MAX_PROJECTION_PAGE_SIZE)throw new IllegalArgumentException("invalid projection page");}
    private GraphConnection resolveTable(String code,String pluginCode){GraphConnection t=graphConnectionRepo.findByCode(code).orElseThrow(()->new ProjectionFailure(PluginGraphErrorCode.TABLE_NOT_FOUND,"Graph table was not found"));if(!t.active())throw new ProjectionFailure(PluginGraphErrorCode.TABLE_DISABLED,"Graph table is not active");if(!t.authorizedFor(pluginCode))throw new ProjectionFailure(PluginGraphErrorCode.TABLE_UNAUTHORIZED,"Graph table is not authorized for this plugin");return t;}
    private List<GraphConnection> boundTables(String pluginCode){return graphConnectionRepo.findActiveAuthorizedByPluginCode(pluginCode,2).stream().filter(t->t!=null&&t.active()&&t.authorizedFor(pluginCode)).toList();}
    private GraphConnection resolveBoundTable(String pluginCode){List<GraphConnection> tables=boundTables(pluginCode);if(tables.isEmpty())throw new ProjectionFailure(PluginGraphErrorCode.TABLE_BINDING_NOT_FOUND,"No active graph table is bound to this plugin");if(tables.size()>1)throw new ProjectionFailure(PluginGraphErrorCode.TABLE_BINDING_AMBIGUOUS,"Multiple active graph tables are bound to this plugin");return tables.getFirst();}
    private PluginGraphTable toSpiTable(GraphConnection table){return new PluginGraphTable(table.getCode(),table.getName(),table.getDescription());}
    private GraphProjection toDomain(PluginGraphProjection p){return new GraphProjection(p.namespace(),p.versionId(),p.nodes().stream().map(n->new GraphProjectionNode(n.id(),n.type(),n.properties())).toList(),p.relationships().stream().map(n->new GraphProjectionRelationship(n.id(),n.type(),n.sourceId(),n.targetId(),n.properties())).toList());}
    private PluginGraphProjectionView toSpi(GraphProjectionView v){return new PluginGraphProjectionView(true,v.namespace(),v.versionId(),new PluginGraphProjectionPage<>(v.nodes().records().stream().map(n->new PluginGraphProjectionNode(n.id(),n.type(),n.properties())).toList(),v.nodes().total(),v.nodes().page(),v.nodes().size()),new PluginGraphProjectionPage<>(v.relationships().records().stream().map(n->new PluginGraphProjectionRelationship(n.id(),n.type(),n.sourceId(),n.targetId(),n.properties())).toList(),v.relationships().total(),v.relationships().page(),v.relationships().size()),null);}
    private void logUnexpectedFailure(String operation,String pluginCode,PluginGraphProjection projection,RuntimeException error){var diagnostic=online.yudream.base.infra.platform.graph.service.Neo4jGraphDatabaseGateway.failureDiagnostics(error);log.error("Plugin graph operation failed: operation={}, pluginCode={}, namespace={}, version={}, nodeCount={}, relationshipCount={}, errorCode={}, errorClass={}, failureType={}, stage={}, batchIndex={}, batchSize={}, neo4jCode={}, gqlStatus={}",operation,pluginCode,projection==null?null:projection.namespace(),projection==null?null:projection.versionId(),projection==null?0:projection.nodes().size(),projection==null?0:projection.relationships().size(),PluginGraphErrorCode.PROJECTION_FAILED,error.getClass().getName(),diagnostic.failureType(),diagnostic.stage(),diagnostic.batchIndex(),diagnostic.batchSize(),diagnostic.neo4jCode(),diagnostic.gqlStatus());}
    private void logUnexpectedFailure(String operation,String pluginCode,GraphProjectionViewRequest request,RuntimeException error){var diagnostic=online.yudream.base.infra.platform.graph.service.Neo4jGraphDatabaseGateway.failureDiagnostics(error);log.error("Plugin graph operation failed: operation={}, pluginCode={}, namespace={}, version={}, nodeCount={}, relationshipCount={}, errorCode={}, errorClass={}, failureType={}, stage={}, batchIndex={}, batchSize={}, neo4jCode={}, gqlStatus={}",operation,pluginCode,request==null?null:request.namespace(),request==null?null:request.versionId(),0,0,PluginGraphErrorCode.PROJECTION_FAILED,error.getClass().getName(),diagnostic.failureType(),diagnostic.stage(),diagnostic.batchIndex(),diagnostic.batchSize(),diagnostic.neo4jCode(),diagnostic.gqlStatus());}
    private PluginGraphProjectionResult failure(PluginGraphErrorCode c,String m){return PluginGraphProjectionResult.failure(c,m);} private PluginGraphProjectionView viewFailure(PluginGraphErrorCode c,String m,PluginGraphProjectionViewRequest r){return PluginGraphProjectionView.failure(c,m,r);} private PluginGraphProjectionView viewFailure(PluginGraphErrorCode c,String m,PluginGraphProjectionReadRequest r){return PluginGraphProjectionView.failure(c,m,r);} private static final class ProjectionFailure extends RuntimeException{private final PluginGraphErrorCode code;private ProjectionFailure(PluginGraphErrorCode c,String m){super(m);code=c;}}
}
