package online.yudream.base.infra.system.security.impl;

import lombok.RequiredArgsConstructor; import online.yudream.base.domain.shared.IdGenerator; import online.yudream.base.domain.system.security.aggregate.ExternalAccount; import online.yudream.base.domain.system.security.repo.ExternalAccountRepo; import online.yudream.base.infra.system.security.dataobj.ExternalAccountDO; import org.springframework.data.mongodb.core.MongoTemplate; import org.springframework.data.mongodb.core.query.Criteria; import org.springframework.data.mongodb.core.query.Query; import org.springframework.stereotype.Service; import java.time.LocalDateTime; import java.util.List; import java.util.Optional;
@Service @RequiredArgsConstructor public class ExternalAccountRepoImpl implements ExternalAccountRepo { private final MongoTemplate mongoTemplate; private final IdGenerator idGenerator;
 public ExternalAccount save(ExternalAccount a){ExternalAccountDO d=toDO(a);if(d.getId()==null){d.setId(idGenerator.nextId());d.setCreateTime(LocalDateTime.now());}d.setUpdateTime(LocalDateTime.now());return toDomain(mongoTemplate.save(d));}
 public Optional<ExternalAccount> findByProviderAndPlatformAndSocialUid(String p,String t,String s){return Optional.ofNullable(toDomain(mongoTemplate.findOne(Query.query(Criteria.where("providerCode").is(p).and("platformType").is(t).and("socialUid").is(s)),ExternalAccountDO.class)));}
 public List<ExternalAccount> findByUserId(Long u){return mongoTemplate.find(Query.query(Criteria.where("userId").is(u)),ExternalAccountDO.class).stream().map(this::toDomain).toList();}
 public Optional<ExternalAccount> findByIdAndUserId(Long i,Long u){return Optional.ofNullable(toDomain(mongoTemplate.findOne(Query.query(Criteria.where("_id").is(i).and("userId").is(u)),ExternalAccountDO.class)));} public void deleteById(Long i){mongoTemplate.remove(Query.query(Criteria.where("_id").is(i)),ExternalAccountDO.class);}
 private ExternalAccountDO toDO(ExternalAccount a){if(a==null)return null;ExternalAccountDO d=new ExternalAccountDO();d.setId(a.getId());d.setVersion(a.getVersion());d.setCreateTime(a.getCreateTime());d.setUpdateTime(a.getUpdateTime());d.setUserId(a.getUserId());d.setProviderCode(a.getProviderCode());d.setPlatformType(a.getPlatformType());d.setSocialUid(a.getSocialUid());d.setNickname(a.getNickname());d.setAvatarUrl(a.getAvatarUrl());d.setGender(a.getGender());d.setLocation(a.getLocation());return d;} private ExternalAccount toDomain(ExternalAccountDO d){return d==null?null:ExternalAccount.builder().id(d.getId()).version(d.getVersion()).createTime(d.getCreateTime()).updateTime(d.getUpdateTime()).userId(d.getUserId()).providerCode(d.getProviderCode()).platformType(d.getPlatformType()).socialUid(d.getSocialUid()).nickname(d.getNickname()).avatarUrl(d.getAvatarUrl()).gender(d.getGender()).location(d.getLocation()).build();}}
