package online.yudream.base.application.system.security.service;

import lombok.RequiredArgsConstructor; import online.yudream.base.application.system.security.cmd.ExternalLoginProviderSaveCmd; import online.yudream.base.application.system.security.dto.*; import online.yudream.base.application.system.user.service.UserAppService; import online.yudream.base.domain.common.exception.BizException; import online.yudream.base.domain.system.security.aggregate.*; import online.yudream.base.domain.system.security.repo.*; import online.yudream.base.domain.system.security.service.ExternalLoginGateway; import online.yudream.base.domain.system.user.aggregate.User; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.util.StringUtils; import java.security.SecureRandom; import java.util.*;
@Service @RequiredArgsConstructor public class ExternalLoginAppService {
 private final ExternalLoginProviderRepo providerRepo; private final ExternalAccountRepo accountRepo; private final ExternalLoginGateway gateway; private final UserAppService userAppService; private final LoginTokenAppService loginTokenAppService; private final Map<String,Session> sessions=new java.util.concurrent.ConcurrentHashMap<>(); private final SecureRandom random=new SecureRandom();
 @Transactional public ExternalLoginProviderDTO saveProvider(ExternalLoginProviderSaveCmd c){String code=StringUtils.hasText(c.getCode())?c.getCode().trim().toLowerCase():"wwoyun";ExternalLoginProvider p=providerRepo.findByCode(code).orElseGet(()->ExternalLoginProvider.builder().code(code).protocol("WWOYUN").build());p.update(c.getName(),c.getAppId(),c.getAppKey(),c.getCallbackUrl(),c.isEnabled(),c.getSupportedTypes());return toProvider(providerRepo.save(p));}
 @Transactional(readOnly=true) public List<ExternalLoginProviderDTO> providers(){return providerRepo.findAll().stream().map(this::toProvider).toList();}
 @Transactional public ExternalLoginAuthorizationDTO authorize(String providerCode,String type,Long bindUserId){ExternalLoginProvider p=active(providerCode);checkType(p,type);String state=state();sessions.put(state,new Session(providerCode,type,bindUserId,System.currentTimeMillis()+600000));return ExternalLoginAuthorizationDTO.builder().state(state).authorizationUrl(gateway.authorizationUrl(p,type,state)).build();}
 @Transactional public LoginTokenDTO callback(String providerCode,String type,String code,String state){Session s=Optional.ofNullable(sessions.remove(state)).filter(v->v.expireAt>System.currentTimeMillis()).orElseThrow(()->new BizException("第三方登录状态已失效"));if(!s.providerCode.equals(providerCode)||!s.type.equals(type))throw new BizException("第三方登录回调不匹配");ExternalLoginProvider p=active(providerCode);ExternalLoginGateway.ExternalIdentity i=gateway.exchange(p,type,code);ExternalAccount a=accountRepo.findByProviderAndPlatformAndSocialUid(providerCode,type,i.socialUid()).orElse(null);Long uid;if(a!=null){uid=a.getUserId();a.refresh(i.nickname(),i.avatarUrl(),i.gender(),i.location());accountRepo.save(a);}else{uid=s.bindUserId!=null?s.bindUserId:userAppService.createExternalUser(i.nickname()).getId();a=ExternalAccount.builder().userId(uid).providerCode(providerCode).platformType(type).socialUid(i.socialUid()).nickname(i.nickname()).avatarUrl(i.avatarUrl()).gender(i.gender()).location(i.location()).build();accountRepo.save(a);}if("qq".equalsIgnoreCase(type))userAppService.bindExternalQq(uid,i.socialUid());return loginTokenAppService.issueForLogin(uid);}
 @Transactional(readOnly=true) public List<ExternalAccountDTO> accounts(Long uid){return accountRepo.findByUserId(uid).stream().map(this::toAccount).toList();}
 @Transactional public void revoke(Long uid,Long id){accountRepo.findByIdAndUserId(id,uid).orElseThrow(()->new BizException("第三方账号不存在"));accountRepo.deleteById(id);}
 @Transactional public void useAvatar(Long uid,Long id){ExternalAccount a=accountRepo.findByIdAndUserId(id,uid).orElseThrow(()->new BizException("第三方账号不存在"));if(!StringUtils.hasText(a.getAvatarUrl()))throw new BizException("该第三方账号没有可用头像");try{java.net.URLConnection c=new java.net.URI(a.getAvatarUrl()).toURL().openConnection();c.setConnectTimeout(10000);c.setReadTimeout(15000);String type=c.getContentType();long size=c.getContentLengthLong();if(!StringUtils.hasText(type)||!type.toLowerCase().startsWith("image/"))throw new BizException("第三方头像不是图片");if(size>10*1024*1024)throw new BizException("第三方头像文件过大");try(java.io.InputStream in=c.getInputStream()){userAppService.updateAvatar(uid,in,"external-avatar",type,size<0?0:size);}}catch(BizException e){throw e;}catch(Exception e){throw new BizException("下载第三方头像失败");}}
 private ExternalLoginProvider active(String code){ExternalLoginProvider p=providerRepo.findByCode(code).orElseThrow(()->new BizException("第三方登录提供方不存在"));if(!p.isEnabled())throw new BizException("第三方登录提供方未启用");if(!"WWOYUN".equals(p.getProtocol()))throw new BizException("暂不支持该第三方登录协议");return p;}private void checkType(ExternalLoginProvider p,String type){if(!StringUtils.hasText(type)||Arrays.stream(p.getSupportedTypes().split(",")).map(String::trim).noneMatch(type::equalsIgnoreCase))throw new BizException("该平台未启用");}private String state(){byte[] b=new byte[20];random.nextBytes(b);return Base64.getUrlEncoder().withoutPadding().encodeToString(b);}private ExternalLoginProviderDTO toProvider(ExternalLoginProvider p){return ExternalLoginProviderDTO.builder().code(p.getCode()).name(p.getName()).protocol(p.getProtocol()).appId(p.getAppId()).callbackUrl(p.getCallbackUrl()).enabled(p.isEnabled()).supportedTypes(p.getSupportedTypes()).updateTime(p.getUpdateTime()).build();}private ExternalAccountDTO toAccount(ExternalAccount a){return ExternalAccountDTO.builder().id(a.getId()).providerCode(a.getProviderCode()).platformType(a.getPlatformType()).socialUid(a.getSocialUid()).nickname(a.getNickname()).avatarUrl(a.getAvatarUrl()).createTime(a.getCreateTime()).build();}private record Session(String providerCode,String type,Long bindUserId,long expireAt){} }
