package online.yudream.base.interfaces.system.security.controller;
import cn.dev33.satoken.stp.StpUtil;import jakarta.validation.Valid;import lombok.RequiredArgsConstructor;import online.yudream.base.application.system.security.service.ExternalLoginAppService;import online.yudream.base.domain.system.security.anno.PermissionRegister;import online.yudream.base.interfaces.common.Result;import online.yudream.base.interfaces.system.security.assembler.ExternalLoginWebAssembler;import online.yudream.base.interfaces.system.security.request.ExternalLoginProviderSaveRequest;import online.yudream.base.interfaces.system.security.res.*;import org.springframework.web.bind.annotation.*;import java.util.List;
@RestController @RequiredArgsConstructor public class ExternalLoginController {private final ExternalLoginAppService app;
 @GetMapping("/api/external-login/providers") public Result<List<ExternalLoginProviderRes>> publicProviders(){return Result.ok(app.providers().stream().map(ExternalLoginWebAssembler::toRes).filter(ExternalLoginProviderRes::isEnabled).toList());}
 @GetMapping("/api/system/security/external-login/providers") @PermissionRegister(code="system:security:external-login:view",name="查看第三方登录",module="系统管理",desc="查看第三方登录配置") public Result<List<ExternalLoginProviderRes>> providers(){return Result.ok(app.providers().stream().map(ExternalLoginWebAssembler::toRes).toList());}
 @PutMapping("/api/system/security/external-login/providers") @PermissionRegister(code="system:security:external-login:edit",name="配置第三方登录",module="系统管理",desc="配置第三方登录提供方") public Result<ExternalLoginProviderRes> save(@Valid @RequestBody ExternalLoginProviderSaveRequest r){return Result.ok(ExternalLoginWebAssembler.toRes(app.saveProvider(ExternalLoginWebAssembler.toCmd(r))));}
 @GetMapping("/api/external-login/{providerCode}/{type}/authorize") public Result<ExternalLoginAuthorizationRes> authorize(@PathVariable String providerCode,@PathVariable String type){return Result.ok(ExternalLoginWebAssembler.toRes(app.authorize(providerCode,type,null)));}
 @GetMapping("/api/external-login/{providerCode}/{type}/callback") public Result<online.yudream.base.application.system.security.dto.LoginTokenDTO> callback(@PathVariable String providerCode,@PathVariable String type,@RequestParam String code,@RequestParam String state){return Result.ok(app.callback(providerCode,type,code,state));}
 @GetMapping("/api/user/me/external-accounts") public Result<List<ExternalAccountRes>> accounts(){return Result.ok(app.accounts(StpUtil.getLoginIdAsLong()).stream().map(ExternalLoginWebAssembler::toRes).toList());}
 @GetMapping("/api/user/me/external-accounts/{providerCode}/{type}/authorize") public Result<ExternalLoginAuthorizationRes> bindAuthorize(@PathVariable String providerCode,@PathVariable String type){return Result.ok(ExternalLoginWebAssembler.toRes(app.authorize(providerCode,type,StpUtil.getLoginIdAsLong())));}
 @DeleteMapping("/api/user/me/external-accounts/{id}") public Result<Void> revoke(@PathVariable Long id){app.revoke(StpUtil.getLoginIdAsLong(),id);return Result.ok();}
 @PostMapping("/api/user/me/external-accounts/{id}/avatar") public Result<Void> useAvatar(@PathVariable Long id){app.useAvatar(StpUtil.getLoginIdAsLong(),id);return Result.ok();}}
